### ISSUE TITLE
[bq E5] [OTA14] Got sound, no picture

### ISSUE THREAD

**Issue by cibersheep** [RyanPattison/Gearboy#1]
Hi. Very nice work and artwork!

When app loads, screen is black (not white) with the text on it.
Loading a rom works and you can hear the first beep but with black screen.

Here's a log that I hope is helpful: http://paste.ubuntu.com/23779035/

Thanks for your work

**Comment by RyanPattison** [comment]
Thank you for your kind words and logs. This sounds like an issue with OpenGL, I'll do my best to get it fixed, but I don't have access to that phone.

**Comment by cibersheep** [comment]
If you need a beta tester, ping me. Here or telegram: @cibersheep

**Comment by RyanPattison** [comment]
Thanks. There is a new release, version 0.4, that fixes a black screen when running on an android phone with OpenGL ES 2 (same as bq E5). Can you verify that version 0.4 fixed this issue?

**Comment by cibersheep** [comment]
I have good and bad news :)
E5 is still showing black screen with "Open ROM" on it as before. But on M10 is working better.

Is there something I can do to give yo more information of the device?

Thanks and keep up the good work!

**Comment by cibersheep** [comment]
Picture is working with the recent changes!
Wwwiiiiiiiiiii

**Comment by RyanPattison** [comment]
Fixed in 0.5
