### ISSUE TITLE
Appena crash at start on nexus 5

### ISSUE THREAD

**Issue by Ataru83** [RyanPattison/Gearboy#11]
Hi 
last (0.8) gearboy crash at start on nexus 5 ( devel-stable). On 0.7 version works well fully working instead previous versions (0.5-0.6) can't see the game but only audio.
Thanks

**Comment by RyanPattison** [comment]
Hello, and thank you for reporting this. It would seem to be a texture format that is at odds with the BQ Aquarius E5. And probably related to #8 . I'll have a fix in the next release, within the next couple days.

**Comment by RyanPattison** [comment]
@Ataru83 Would you be able to compile and test the latest version on your Nexus 5?

**Comment by Ataru83** [comment]
I never done but I will try or can you give me a prebuild version?

**Comment by RyanPattison** [comment]
I just released the update to the store as version 0.9. Please post if it works or not. If not, post the log (there are instructions on the wiki page). I can help you set up compiling if you'd like that too.

**Comment by Ataru83** [comment]
Thanks ver. 0.9 works good on my Nexus 5!
