### ISSUE TITLE
[bq M10] [OTA14] [0.4] No save game

### ISSUE THREAD

**Issue by cibersheep** [RyanPattison/Gearboy#2]
[edit]
*Saved games doesn't load on start (Tested with Final Fantasy Legends -SAGA-and Ultima Runes of Virtue -RUNESOFVI.

[solved on 0.4]
Games often don't load.
*Loading rom often doesn't work (with same rom). I have tried to reproduce the behaviour (and this is going to sound silly but) I think:
a)
 - Open app
 - Tap on screen, select folder.
 - Select file, wait some seconds, tap on open > rom doesn't load
b)
 - Open app
 - Tap on screen, select folder.
 - Select file, and quickly tap on open > rom loads
paste.ubuntu.com/23779248/
c)
 - With one game opened
 - tap on screen, select folder, file and open.
 - App freezes.
http://paste.ubuntu.com/23779276/

Thanks!

**Comment by RyanPattison** [comment]
Fixed in 0.4
