### ISSUE TITLE
No Game Display On Nexus 4

### ISSUE THREAD

**Issue by universal11** [RyanPattison/Gearboy#8]
Installed this on a Nexus 4 with Ubuntu Touch OTA-15 installed. When a game is loaded there is no display shown, only audio.

**Comment by RyanPattison** [comment]
Hi, thanks for submitting an issue. Is this version 0.5 on the store or the latest in github?

**Comment by universal11** [comment]
The issue exists in both versions. (I've tried both)

**Comment by RyanPattison** [comment]
Is the game screen black or white?

**Comment by RyanPattison** [comment]
Can you post the logs for the github version?

**Comment by RyanPattison** [comment]
This may be fixed in the latest commit. An android device was showing all controls and no screen (just the normal background colour) and played audio. The problem was related to an outdated enum for the texture format. I don't have a Nexus 4 device to verify the fix though.

**Comment by universal11** [comment]
I have confirmed that the latest build from the app store is now working on my Nexus 4.
